language: rust
rust:
    - nightly
    - beta
    - stable
addons:
    apt:
        packages:
        - libasound2-dev
script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo test --no-default-features --features "flac" --verbose
    - cargo test --no-default-features --features "ogg_vorbis" --verbose
    - cargo test --no-default-features --features "wav" --verbose
    - cargo test --no-default-features --features "caf_alac" --verbose
    - cargo doc --verbose
